%YAML:1.0

# output directory
output_dir: "/home/itaouil/datasets/VIO/FPV/"

# switches
if_FEJ: 1    # 0(false) or 1(true)
estimate_extrin: 1    # 0(false) or 1(true)
estimate_td: 1    # 0(false) or 1(true)
calib_imu_instrinsic: 0    # 0(false) or 1(true)

# camera instrinsic
camera_model: "pinhole"       # only support "pinhole"
distortion_model: "equidistant"    # only support "radtan" and "equidistant"
resolution_width: 640
resolution_height: 480
intrinsics:
   fx: 277.4786896484645
   fy: 277.42548548840034
   cx: 320.1052053576385
   cy: 242.10083077857894
distortion_coeffs:
   k1: -0.005719912631104124
   k2: 0.004742449009601135
   p1: 0.0012060658036136048
   p2: -0.001580292679344826

# imu-camera extrinsic, including spacial and temporal parameters
T_cam_imu: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data:
    [-0.03179778293757218, -0.9994933985910031, -0.001359107523862424, 0.021115239798621798,
     0.012827844120885779, 0.0009515801497960164, -0.9999172670328424, -0.0008992998316121829,
     0.9994120008362244, -0.03181258663210035, 0.012791087377928778, -0.009491094814035777,
     0.0, 0.0, 0.0, 1.0]
td: 0.0

# TODO: if calibrate camera instrinsic online

# visual front-end parameters
pyramid_levels: 2
patch_size: 15
fast_threshold: 30
max_iteration: 30
track_precision: 0.01
ransac_threshold: 1
max_features_num: 230
min_distance: 15
flag_equalize: 1    # 0(false) or 1(true)
pub_frequency: 35

# window size
sw_size: 10

# online reset thresholds
position_std_threshold: 8.0
rotation_threshold: 0.2618
translation_threshold: 0.4
tracking_rate_threshold: 0.5

# feature triangulation parameters
least_observation_number: 3
max_track_len: 10
feature_translation_threshold: -1.0

# imu and camera measurement noise parameters
noise_gyro: 0.004
noise_acc: 0.08
noise_gyro_bias: 2e-6
noise_acc_bias: 4e-5
noise_feature: 0.008

# filter intial covariance
initial_covariance_orientation: 4e-4
initial_covariance_velocity: 0.25
initial_covariance_position: 1.0
initial_covariance_gyro_bias: 4e-4
initial_covariance_acc_bias: 0.01
initial_covariance_extrin_rot: 3.0462e-8
initial_covariance_extrin_trans: 9e-8

# fej settings
reset_fej_threshold: 10.11

# zupt settings
if_ZUPT_valid: 1    # 0(false) or 1(true)
zupt_max_feature_dis: 2e-3
zupt_noise_v: 1e-2    # std
zupt_noise_p: 1e-2
zupt_noise_q: 3.4e-2

# static initialization setting
static_duration: 1.0

# measurement rate
imu_rate: 500
img_rate: 30

# augmented feature state settings
max_features_in_one_grid: 1     # pure msckf if set to 0
aug_grid_rows: 5
aug_grid_cols: 6
feature_idp_dim: 1              # 1 or 3

# if apply Schmidt filter
use_schmidt: 0    # 0(false) or 1(true)
